### ISSUE TITLE
Have a --version flag to print version info.

### ISSUE THREAD

**Issue by torinmr** [gopatchy/bkl#6]
**Description**
I'm never going to remember `BKL_VERSION=1 bkl` without looking it up.

**Comment by flamingcow66** [comment]
Reasonable request. I didn't add this initially because some of the apps (e.g. `kubectl-bkl`) can't take flags because they pass them through. That's not a good argument for `bkl` itself not taking arguments though.

**Comment by flamingcow66** [comment]
Fixed in 1fa958f3d40d3172eafba3d025ef23a8d818512c, releasing in `v1.0.30`.
